export const MOCK_SPREADSHEET = {
  id: 1,
  title: "Природа",
  parentCell: null,
  rows: [
    {
      id: 1,
      title: "",
      color: null,
      sequence: 1,
      isTimeScale: false,
      cells: [
        {
          id: 1,
          sequence: 1,
          title: "Тестовое маапвапвыап",
          isTitleVisible: null,
          type: "text",
          description:
            "АААААААААААААААААААААААААААБЛЯТЬ Я несколько устал жить эту жихнь и очень хочу кушать. Ну там это лорем ипсум хуипсумLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. \r\nfdgdfgdf\r\n\r\n\r\n\r\n\r\n\r\nААААААААААААААААААААААААААААААААААААААААААААААААААААААААААА\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\nКак бы еще поругаться",
          images: [],
          files: [],
        },
        {
          id: 47,
          sequence: 1,
          title: "чето",
          isTitleVisible: null,
          type: "media",
          description: "",
          images: [],
          files: [],
        },
        {
          id: 12,
          sequence: 2,
          title: null,
          isTitleVisible: null,
          type: null,
          description: null,
          images: [],
          files: [],
        },
        {
          id: 13,
          sequence: 2,
          title: "АААААААААААААААААА",
          isTitleVisible: null,
          type: "text",
          description: "Провер очка",
          images: [],
          files: [],
        },
        {
          id: 14,
          sequence: 2,
          title: null,
          isTitleVisible: null,
          type: null,
          description: null,
          images: [],
          files: [],
        },
        {
          id: 15,
          sequence: 2,
          title: null,
          isTitleVisible: null,
          type: null,
          description: null,
          images: [],
          files: [],
        },
        {
          id: 16,
          sequence: 2,
          title: null,
          isTitleVisible: null,
          type: null,
          description: null,
          images: [],
          files: [],
        },
        {
          id: 48,
          sequence: 2,
          title: null,
          isTitleVisible: null,
          type: null,
          description: null,
          images: [],
          files: [],
        },
        {
          id: 49,
          sequence: 3,
          title: null,
          isTitleVisible: null,
          type: null,
          description: null,
          images: [],
          files: [],
        },
      ],
    },
    {
      id: 2,
      title: "Название строки",
      color: null,
      sequence: 1,
      isTimeScale: false,
      cells: [
        {
          id: 2,
          sequence: 1,
          title: null,
          isTitleVisible: null,
          type: null,
          description: null,
          images: [],
          files: [],
        },
        {
          id: 3,
          sequence: 2,
          title: null,
          isTitleVisible: null,
          type: null,
          description: null,
          images: [],
          files: [],
        },
        {
          id: 5,
          sequence: 2,
          title: "Блин надо сделать название обязательным",
          isTitleVisible: null,
          type: "text",
          description: "",
          images: [],
          files: [],
        },
        {
          id: 6,
          sequence: 2,
          title: null,
          isTitleVisible: null,
          type: null,
          description: null,
          images: [],
          files: [],
        },
        {
          id: 7,
          sequence: 2,
          title: null,
          isTitleVisible: null,
          type: null,
          description: null,
          images: [],
          files: [],
        },
        {
          id: 25,
          sequence: 2,
          title: null,
          isTitleVisible: null,
          type: null,
          description: null,
          images: [],
          files: [],
        },
        {
          id: 26,
          sequence: 2,
          title: null,
          isTitleVisible: null,
          type: null,
          description: null,
          images: [],
          files: [],
        },
        {
          id: 35,
          sequence: 2,
          title: null,
          isTitleVisible: null,
          type: null,
          description: null,
          images: [],
          files: [],
        },
        {
          id: 44,
          sequence: 2,
          title: null,
          isTitleVisible: null,
          type: null,
          description: null,
          images: [],
          files: [],
        },
      ],
    },
    {
      id: 4,
      title: "Новая строка",
      color: null,
      sequence: 1,
      isTimeScale: false,
      cells: [],
    },
    {
      id: 3,
      title: "Другая строка",
      color: null,
      sequence: 2,
      isTimeScale: false,
      cells: [
        {
          id: 4,
          sequence: 1,
          title: null,
          isTitleVisible: null,
          type: null,
          description: null,
          images: [],
          files: [],
        },
        {
          id: 8,
          sequence: 2,
          title: null,
          isTitleVisible: null,
          type: null,
          description: null,
          images: [],
          files: [],
        },
        {
          id: 9,
          sequence: 2,
          title: null,
          isTitleVisible: null,
          type: null,
          description: null,
          images: [],
          files: [],
        },
        {
          id: 10,
          sequence: 2,
          title: null,
          isTitleVisible: null,
          type: null,
          description: null,
          images: [],
          files: [],
        },
        {
          id: 11,
          sequence: 2,
          title: null,
          isTitleVisible: null,
          type: null,
          description: null,
          images: [],
          files: [],
        },
      ],
    },
    {
      id: 7,
      title: "asd Название строки",
      color: null,
      sequence: 3,
      isTimeScale: false,
      cells: [
        {
          id: 27,
          sequence: 1,
          title: null,
          isTitleVisible: null,
          type: null,
          description: null,
          images: [],
          files: [],
        },
        {
          id: 28,
          sequence: 2,
          title: null,
          isTitleVisible: null,
          type: null,
          description: null,
          images: [],
          files: [],
        },
      ],
    },
    {
      id: 9,
      title: "asd Название строки",
      color: null,
      sequence: 3,
      isTimeScale: false,
      cells: [
        {
          id: 36,
          sequence: 1,
          title: null,
          isTitleVisible: null,
          type: null,
          description: null,
          images: [],
          files: [],
        },
        {
          id: 37,
          sequence: 2,
          title: null,
          isTitleVisible: null,
          type: null,
          description: null,
          images: [],
          files: [],
        },
      ],
    },
    {
      id: 11,
      title: "asd Название строки",
      color: null,
      sequence: 3,
      isTimeScale: false,
      cells: [
        {
          id: 45,
          sequence: 1,
          title: null,
          isTitleVisible: null,
          type: null,
          description: null,
          images: [],
          files: [],
        },
        {
          id: 46,
          sequence: 2,
          title: null,
          isTitleVisible: null,
          type: null,
          description: null,
          images: [],
          files: [],
        },
      ],
    },
    {
      id: 5,
      title: "Еще Новая строка",
      color: null,
      sequence: 5,
      isTimeScale: false,
      cells: [
        {
          id: 17,
          sequence: 1,
          title: null,
          isTitleVisible: null,
          type: null,
          description: null,
          images: [],
          files: [],
        },
        {
          id: 18,
          sequence: 2,
          title: null,
          isTitleVisible: null,
          type: null,
          description: null,
          images: [],
          files: [],
        },
        {
          id: 19,
          sequence: 3,
          title: null,
          isTitleVisible: null,
          type: null,
          description: null,
          images: [],
          files: [],
        },
        {
          id: 20,
          sequence: 4,
          title: null,
          isTitleVisible: null,
          type: null,
          description: null,
          images: [],
          files: [],
        },
      ],
    },
    {
      id: 6,
      title: "Еще Новая строка",
      color: null,
      sequence: 5,
      isTimeScale: false,
      cells: [
        {
          id: 21,
          sequence: 1,
          title: null,
          isTitleVisible: null,
          type: null,
          description: null,
          images: [],
          files: [],
        },
        {
          id: 22,
          sequence: 2,
          title: null,
          isTitleVisible: null,
          type: null,
          description: null,
          images: [],
          files: [],
        },
        {
          id: 23,
          sequence: 3,
          title: null,
          isTitleVisible: null,
          type: null,
          description: null,
          images: [],
          files: [],
        },
        {
          id: 24,
          sequence: 4,
          title: null,
          isTitleVisible: null,
          type: null,
          description: null,
          images: [],
          files: [],
        },
      ],
    },
    {
      id: 8,
      title: "",
      color: null,
      sequence: 7,
      isTimeScale: false,
      cells: [
        {
          id: 29,
          sequence: 1,
          title: null,
          isTitleVisible: null,
          type: null,
          description: null,
          images: [],
          files: [],
        },
        {
          id: 30,
          sequence: 2,
          title: null,
          isTitleVisible: null,
          type: null,
          description: null,
          images: [],
          files: [],
        },
        {
          id: 31,
          sequence: 3,
          title: null,
          isTitleVisible: null,
          type: null,
          description: null,
          images: [],
          files: [],
        },
        {
          id: 32,
          sequence: 4,
          title: null,
          isTitleVisible: null,
          type: null,
          description: null,
          images: [],
          files: [],
        },
        {
          id: 33,
          sequence: 5,
          title: null,
          isTitleVisible: null,
          type: null,
          description: null,
          images: [],
          files: [],
        },
        {
          id: 34,
          sequence: 6,
          title: null,
          isTitleVisible: null,
          type: null,
          description: null,
          images: [],
          files: [],
        },
      ],
    },
    {
      id: 10,
      title: "",
      color: null,
      sequence: 9,
      isTimeScale: false,
      cells: [
        {
          id: 38,
          sequence: 1,
          title: null,
          isTitleVisible: null,
          type: null,
          description: null,
          images: [],
          files: [],
        },
        {
          id: 39,
          sequence: 2,
          title: null,
          isTitleVisible: null,
          type: null,
          description: null,
          images: [],
          files: [],
        },
        {
          id: 40,
          sequence: 3,
          title: null,
          isTitleVisible: null,
          type: null,
          description: null,
          images: [],
          files: [],
        },
        {
          id: 41,
          sequence: 4,
          title: null,
          isTitleVisible: null,
          type: null,
          description: null,
          images: [],
          files: [],
        },
        {
          id: 42,
          sequence: 5,
          title: null,
          isTitleVisible: null,
          type: null,
          description: null,
          images: [],
          files: [],
        },
        {
          id: 43,
          sequence: 6,
          title: null,
          isTitleVisible: null,
          type: null,
          description: null,
          images: [],
          files: [],
        },
      ],
    },
    {
      id: 12,
      title: "",
      color: null,
      sequence: 12,
      isTimeScale: false,
      cells: [
        {
          id: 50,
          sequence: 1,
          title: null,
          isTitleVisible: null,
          type: null,
          description: null,
          images: [],
          files: [],
        },
        {
          id: 51,
          sequence: 2,
          title: null,
          isTitleVisible: null,
          type: null,
          description: null,
          images: [],
          files: [],
        },
        {
          id: 52,
          sequence: 3,
          title: null,
          isTitleVisible: null,
          type: null,
          description: null,
          images: [],
          files: [],
        },
        {
          id: 53,
          sequence: 4,
          title: null,
          isTitleVisible: null,
          type: null,
          description: null,
          images: [],
          files: [],
        },
        {
          id: 54,
          sequence: 5,
          title: null,
          isTitleVisible: null,
          type: null,
          description: null,
          images: [],
          files: [],
        },
        {
          id: 55,
          sequence: 6,
          title: null,
          isTitleVisible: null,
          type: null,
          description: null,
          images: [],
          files: [],
        },
        {
          id: 56,
          sequence: 7,
          title: null,
          isTitleVisible: null,
          type: null,
          description: null,
          images: [],
          files: [],
        },
        {
          id: 57,
          sequence: 8,
          title: null,
          isTitleVisible: null,
          type: null,
          description: null,
          images: [],
          files: [],
        },
        {
          id: 58,
          sequence: 9,
          title: null,
          isTitleVisible: null,
          type: null,
          description: null,
          images: [],
          files: [],
        },
      ],
    },
  ],
};
